### ISSUE TITLE
'Rotate 2D image on GPU' not working on single plane images

### ISSUE THREAD

**Issue by iwbh15** [clij/clij#32]
CLIJ/Transform/Rotate 2D image on GPU 
is not working on GeForce GTX 1060 with single plane 8/16/32 bit images.
The resulting image is black for the different type of images.
If an additional (empty/black) plane is added to the image and it becomes a stack then the result of the rotation is as expected.

On the same laptop the GPU-based rotation is working correctly with single plane images on the in-build Intel(R) UHD Graphics 630 GPU.

CLIJ 1.0.7
FIJI / ImageJ 2.0.0-rc-69/1.52p
Java 1.8.0_172 (64-bit)
Windows10 64

**Comment by iwbh15** [comment]
2D Rotation added to clij/clij-core.
Problems seems due to OpenCL version or implementation.

=> Issue will be closed.

**Comment by haesleinhuepf** [comment]
Oh great, thanks for reporting and fixing the bug. That's a really good bugfix. I will knit it into clij-core as you suggested! Thanks a bunch! :-)
